### ISSUE TITLE
When the file don't have hash from server, duplicate file check will fail and create new part file.

### ISSUE THREAD

**Issue by yuban01652** [L4cache/kemono-dl#38]
### Version

Version: 2024.02.02 (Actually, the latest)

### Your Command

```bash

python kemono-dl.py --cookies "cookie.txt" --links https://kemono.su/subscribestar/user/Gerph --inline --content --filename-pattern "{published} {title}/{index}_{filename}.{ext}" --inline-filename-pattern "{published} {title}/{index}.{ext}" --other-filename-pattern "{published} {title}/{filename}.{ext}" --date-strf-pattern "%y-%m-%d" --skip-filetypes psd,clip

```

### Description of bug

When downloading a file from a server without hash, the program will warn "WARNING:No hash from server! | Saving file with suffix in name". Then If the file already exists, the script will still attempt to download the file and pop up " FileExistsError: [WinError 183] Cannot create a file when that file already exists" when creating the file. Then a new part file will be generated in the folder.

### How To Reproduce

Try downloading "subscribestar/user/Gerph" files twice.

### Error messages and tracebacks

```python

2024-12-29 08:24:44,829:INFO:Downloading Post | Misty and Croconaw training
2024-12-29 08:24:44,829:DEBUG:Post URL: https://kemono.su/subscribestar/user/Gerph/post/101935
2024-12-29 08:24:44,831:INFO:Downloading: 1_MISTY.jpg
2024-12-29 08:24:44,831:DEBUG:Downloading from: https://kemono.su/data/attachments/subscribestar/Gerph/101935/MISTY.jpg
2024-12-29 08:24:44,832:DEBUG:Downloading to: Downloads\subscribestar\Gerph [Gerph]\20-04-03 Misty and Croconaw training\1_MISTY.jpg.part
2024-12-29 08:24:51,401:DEBUG:Local File hash: 69c71bb8b442b61b113a09b5a2a92c69ebae54585193ad199031e4a649b2b547
2024-12-29 08:24:51,402:DEBUG:Sever File hash: None
2024-12-29 08:24:51,402:WARNING:No hash from server! | Saving file with suffix in name
2024-12-29 08:24:51,403:ERROR:Failed to download: Downloads\subscribestar\Gerph [Gerph]\20-04-03 Misty and Croconaw training\1_MISTY.jpg
Traceback (most recent call last):
  File "[my path]\kemono-dl-main-L4cache\src\main.py", line 555, in download_attachments
    self.download_file(file, retry=self.retry, post=post)
  File "[my path]\kemono-dl-main-L4cache\src\main.py", line 811, in download_file
    os.rename(part_file, filepath)
FileExistsError: [WinError 183]  Cannot create a file when that file already exists: 'Downloads\\subscribestar\\Gerph [Gerph]\\20-04-03 Misty and Croconaw training\\1_MISTY.jpg.part' -> 'Downloads\\subscribestar\\Gerph [Gerph]\\20-04-03 Misty and Croconaw training\\1_MISTY_noserverhash.jpg'

```

### Additional comments

I think this may be because the script only checked the original name file and did not check files with '_noserverhash'.

**Comment by L4cache** [comment]
My intention was that you should verify those files and if they are correct, remove the suffix...

**Comment by yuban01652** [comment]
Ok......? After all, sometimes a lot of suffix files are generated, and there is no guide in the README, which makes me a bit confused. Anyway, thank you.
